name = "simplifile"
version = "2.7.0"
description = "Basic file operations that work on all targets (macabre python-target port of simplifile)"

licences = ["Apache-2.0"]
repository = { type = "github", user = "dusty-phillips", repo = "macabre_simplifile" }

[dependencies]
gleam_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }
macabre_filepath = { git = "git@github.com:dusty-phillips/macabre_filepath.git", ref = "main" }

[dev-dependencies]
gleeunit = { git = "git@github.com:dusty-phillips/macabre_gleeunit.git", ref = "main" }
